import type { Metadata } from "next";import Link from "next/link";import { notFound } from "next/navigation";
const content:Record<string,{title:string,kicker:string,body:string[]}>={
 faq:{title:"Dúvidas frequentes",kicker:"Tudo o que você precisa saber",body:["Como recebo minha apostila? Na operação real, o acesso é liberado na biblioteca após a confirmação do pagamento.","O PDF é personalizado? Sim. A especificação prevê senha de abertura pelo CPF e marca d’água individual.","Posso solicitar reembolso? A garantia proposta é de 7 dias, conforme o Código de Defesa do Consumidor."]},
 contato:{title:"Fale com a Facil Digital+",kicker:"Estamos aqui para ajudar",body:["Atendimento demonstrativo: segunda a sexta, das 9h às 18h.","WhatsApp e formulário real serão conectados na implantação comercial.","Para esta versão, nenhum dado enviado é armazenado."]},
 privacidade:{title:"Privacidade e LGPD",kicker:"Seus dados merecem cuidado",body:["A solução foi especificada com minimização de dados, consentimento explícito e autoatendimento para exportação e exclusão.","O CPF não deve aparecer em URLs, nomes de arquivos ou registros técnicos.","Analytics e cookies devem respeitar a escolha do visitante. Este protótipo não coleta dados pessoais."]},
 termos:{title:"Termos de uso",kicker:"Relação clara desde o início",body:["Os materiais demonstrados neste site são fictícios e não estão disponíveis para compra real.","Na versão comercial, condições de acesso, atualização, uso individual e proteção do conteúdo serão apresentadas antes da compra.","O conteúdo adquirido será licenciado para uso pessoal do aluno."]},
 reembolso:{title:"Garantia e reembolso",kicker:"Sete dias para decidir com tranquilidade",body:["A proposta comercial prevê garantia incondicional de 7 dias após a compra.","O pedido poderá ser feito na área do aluno e será processado pelo mesmo meio de pagamento.","Após a confirmação, o acesso ao material será revogado automaticamente."]},
 obrigado:{title:"Você entrou no radar.",kicker:"Cadastro demonstrativo concluído",body:["Nenhum dado foi armazenado nesta demonstração.","Na versão comercial, você receberá uma confirmação por e-mail antes de ativar os alertas.","Enquanto isso, explore os materiais fictícios e conheça a experiência."]},
};
export function generateStaticParams(){return Object.keys(content).map(page=>({page}))}
export async function generateMetadata({params}:{params:Promise<{page:string}>}):Promise<Metadata>{const {page}=await params;return content[page]?{title:content[page].title}:{}}
export default async function InfoPage({params}:{params:Promise<{page:string}>}){const {page}=await params;const item=content[page];if(!item)notFound();return <main className="simple-page"><section className="simple-hero"><div className="container"><span className="eyebrow eyebrow-light"><i/>{item.kicker}</span><h1>{item.title}</h1></div></section><section className="container info-content">{item.body.map((p,i)=><article key={p}><span>{String(i+1).padStart(2,"0")}</span><p>{p}</p></article>)}<Link className="button button-primary" href="/apostilas">Explorar apostilas →</Link></section></main>}
