"use client";
import Link from "next/link";
import { useState } from "react";
import { formatPrice } from "../lib/currency";
import { useShop } from "./shop-provider";
export function CheckoutDemo(){
 const {cart}=useShop();const [method,setMethod]=useState("pix");const [coupon,setCoupon]=useState("");const [applied,setApplied]=useState(false);const [done,setDone]=useState(false);
 const subtotal=cart.reduce((s,i)=>s+i.price,0);const discount=(method==="pix"?subtotal*.05:0)+(applied?10:0);const total=Math.max(0,subtotal-discount);
 if(done)return <main className="checkout-success"><div><span>✓</span><small>DEMONSTRAÇÃO CONCLUÍDA</small><h1>Seu pedido de teste foi recebido.</h1><p>Nenhuma cobrança foi realizada. Em produção, esta tela exibirá o recibo e liberará o acesso após a confirmação do Mercado Pago.</p><Link className="button button-primary" href="/minha-conta">Conhecer a área do aluno →</Link></div></main>
 return <main className="checkout-page"><div className="container checkout-heading"><span className="eyebrow"><i/> Ambiente seguro</span><h1>Falta pouco para começar.</h1><p>Este checkout é uma simulação visual. Nenhuma cobrança será feita.</p></div><div className="container checkout-grid"><form className="checkout-form" onSubmit={e=>{e.preventDefault();setDone(true)}}>
  <section><header><span>1</span><div><h2>Seus dados</h2><p>Usados para liberar e proteger o material.</p></div></header><div className="field-grid"><label>Nome completo<input required placeholder="Como no documento"/></label><label>E-mail<input required type="email" placeholder="voce@email.com"/></label><label>CPF<input required placeholder="000.000.000-00"/></label><label>Telefone<input required placeholder="(00) 00000-0000"/></label></div><small className="privacy-note">♢ O CPF será usado como senha do PDF e nunca aparecerá em URLs ou nomes de arquivo.</small></section>
  <section><header><span>2</span><div><h2>Pagamento</h2><p>Escolha a melhor forma para você.</p></div></header><div className="payment-tabs">{[["pix","PIX","5% OFF"],["card","Cartão","até 12x"],["boleto","Boleto","à vista"]].map(m=><button type="button" key={m[0]} onClick={()=>setMethod(m[0])} className={method===m[0]?"active":""}><b>{m[1]}</b><small>{m[2]}</small></button>)}</div>{method==="pix"?<div className="payment-demo"><span>◇</span><div><h3>PIX com desconto</h3><p>O QR Code será gerado após confirmar. Validade de 30 minutos.</p></div></div>:method==="card"?<div className="field-grid"><label>Número do cartão<input placeholder="0000 0000 0000 0000"/></label><label>Nome impresso<input placeholder="NOME NO CARTÃO"/></label><label>Validade<input placeholder="MM/AA"/></label><label>CVV<input placeholder="000"/></label></div>:<div className="payment-demo"><span>▤</span><div><h3>Boleto bancário</h3><p>O acesso será liberado após a compensação, normalmente em 1 dia útil.</p></div></div>}<button className="button button-accent submit-order" disabled={!cart.length} type="submit">{cart.length?"Confirmar pedido demonstrativo →":"Adicione um material primeiro"}</button><small className="demo-disclaimer">Integração real com Mercado Pago, HMAC e webhooks depende das credenciais de produção.</small></section>
 </form><aside className="order-summary"><span>RESUMO DO PEDIDO</span>{cart.length?cart.map(i=><article key={i.slug}><div className={`tiny-cover ${i.coverClass}`}/><div><strong>{i.title}</strong><small>Digital • acesso imediato</small></div><b>{formatPrice(i.price)}</b></article>):<div className="checkout-empty"><p>Seu carrinho está vazio.</p><Link href="/apostilas">Escolher uma apostila →</Link></div>}<div className="coupon"><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="Cupom: APROVA10"/><button type="button" onClick={()=>setApplied(coupon.toUpperCase()==="APROVA10")}>Aplicar</button></div>{coupon&&<small className={applied?"coupon-ok":"coupon-hint"}>{applied?"Cupom aplicado: R$ 10,00 de desconto":"Use APROVA10 nesta demonstração."}</small>}<dl><div><dt>Subtotal</dt><dd>{formatPrice(subtotal)}</dd></div><div><dt>Descontos</dt><dd>- {formatPrice(discount)}</dd></div><div><dt>Total</dt><dd>{formatPrice(total)}</dd></div></dl><footer><span>♢ Pagamento protegido</span><span>7 Garantia de 7 dias</span></footer></aside></div></main>
}
